# Generated by Django 5.1.1 on 2024-09-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfInventoryNumberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_type', models.CharField(max_length=100, verbose_name='Название документации')),
                ('number_of_code_in_ms_access', models.IntegerField(verbose_name='КодТипИнв в MS Access')),
            ],
        ),
    ]
