# Generated by Django 5.1.1 on 2024-10-01 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_inventory_app', '0002_typeofinventorynumbermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeofinventorynumbermodel',
            options={'verbose_name': 'тип инвентарного номера', 'verbose_name_plural': 'типы инвентарных номеров'},
        ),
        migrations.AlterField(
            model_name='closeinventorynumbersmodel',
            name='general_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='get_inventory_app.generalinfoinventorynumbermodel', verbose_name='Общая информация'),
        ),
        migrations.AlterField(
            model_name='ktinventorynumbersmodel',
            name='general_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='get_inventory_app.generalinfoinventorynumbermodel', verbose_name='Общая информация'),
        ),
        migrations.AlterField(
            model_name='openinventorynumbersmodel',
            name='general_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='get_inventory_app.generalinfoinventorynumbermodel', verbose_name='Общая информация'),
        ),
    ]
