# Generated by Django 5.1.1 on 2024-10-30 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_inventory_app', '0004_typeofpermissionnumbermodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeofpermissionnumbermodel',
            options={'verbose_name': 'тип номера на разрешение', 'verbose_name_plural': 'типы номеров на разрешения'},
        ),
        migrations.AddField(
            model_name='generalinfoinventorynumbermodel',
            name='cpe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpe_employee', to='get_inventory_app.employeemodel', verbose_name='ГИП'),
        ),
        migrations.AlterField(
            model_name='generalinfoinventorynumbermodel',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_employee', to='get_inventory_app.employeemodel', verbose_name='Сотрудник'),
        ),
    ]
