# Generated by Django 5.1.1 on 2024-11-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_inventory_app', '0006_generalinfopermissionnumbermodel_cpe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Наименование альбома')),
                ('file_path', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Путь к файлу')),
                ('md5_file', models.CharField(blank=True, max_length=250, null=True, verbose_name='md5 файла')),
                ('data_create', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'архивный файл',
                'verbose_name_plural': 'архивные файлы',
            },
        ),
        migrations.AlterModelOptions(
            name='replacementpermissionnumbersmodel',
            options={'verbose_name': 'открытый инвентарный номер', 'verbose_name_plural': 'открытые инвентарные номера'},
        ),
    ]
