# Generated by Django 5.1.1 on 2024-11-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_inventory_app', '0007_archivefilesmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivefilesmodel',
            name='file_size',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Размер файла'),
        ),
    ]
