# Generated by Django 5.1.1 on 2024-11-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_inventory_app', '0008_archivefilesmodel_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivefilesmodel',
            name='album_name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Наименование альбома'),
        ),
        migrations.AlterField(
            model_name='archivefilesmodel',
            name='md5_file',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='md5 файла'),
        ),
    ]
