# Generated by Django 5.1.1 on 2024-11-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_inventory_app', '0009_alter_archivefilesmodel_album_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivefilesmodel',
            name='file_was_deleted',
            field=models.BooleanField(default=False, verbose_name='Файл был удален'),
        ),
    ]
