# Generated by Django 5.1.1 on 2024-11-20 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_inventory_app', '0010_archivefilesmodel_file_was_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsDownloadsAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_file_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Название скаченного альбома')),
                ('download_emp_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя сотрудника скачавшего')),
                ('download_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время скачивания')),
                ('download_emp_Key', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='get_inventory_app.employeemodel', verbose_name='id сотрудника скачавшего')),
                ('download_file_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='get_inventory_app.archivefilesmodel', verbose_name='id скаченного альбома')),
            ],
            options={
                'verbose_name': 'log загрузки',
                'verbose_name_plural': 'logs закгрузок',
            },
        ),
    ]
