# Generated by Django 5.1.1 on 2024-11-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_inventory_app', '0011_logsdownloadsalbum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivefilesmodel',
            name='album_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Наименование альбома'),
        ),
    ]
