# Generated by Django 5.1.1 on 2024-11-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_inventory_app', '0012_alter_archivefilesmodel_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsdownloadsalbum',
            name='download_emp_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя сотрудника скачавшего'),
        ),
        migrations.AlterField(
            model_name='logsdownloadsalbum',
            name='download_file_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название скаченного альбома'),
        ),
    ]
