# Generated by Django 5.1.1 on 2024-11-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_inventory_app', '0013_alter_logsdownloadsalbum_download_emp_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveEditableFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Наименование архива')),
                ('file_path', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Путь к файлу')),
                ('file_size', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Размер файла')),
                ('md5_file', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='md5 файла')),
                ('data_create', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего обновления')),
                ('file_was_deleted', models.BooleanField(default=False, verbose_name='Файл был удален')),
            ],
            options={
                'verbose_name': 'файл в редактируемом формате',
                'verbose_name_plural': 'файлы в редактируемом формате',
            },
        ),
    ]
