# Generated by Django 5.1.1 on 2024-12-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_inventory_app', '0014_archiveeditablefilesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintPagePermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'сотрудник имеющий доступ к странице печати',
                'verbose_name_plural': 'сотрудники имеющие доступ к странице печати',
                'db_table': 'page_calculator_app_printpagepermissionmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountsFilesInArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_pdf', models.IntegerField(blank=True, null=True, verbose_name='Количество pdf файлов')),
                ('count_editable', models.IntegerField(blank=True, null=True, verbose_name='Количество zip файлов')),
                ('date_of_update_counts', models.IntegerField(blank=True, null=True, verbose_name='Количество добавленных файлов')),
                ('date_log', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время обновления')),
            ],
            options={
                'verbose_name': 'количество файлов',
                'verbose_name_plural': 'количество файлов',
            },
        ),
    ]
