# Generated by Django 5.1.1 on 2024-12-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_inventory_app', '0015_printpagepermissionmodel_countsfilesinarchive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countsfilesinarchive',
            old_name='date_of_update_counts',
            new_name='count_of_add_files',
        ),
    ]
